version: 2.1

orbs:
  node: circleci/node@5.1.0

workflows:
  testing:
    jobs:
      - node/test:
          version: '18.17'
          pkg-manager: npm
          run-command: test:std
          resource_class: small
